name: chess_vectors_flutter
description: Chess pieces vectors for Flutter. These vectors are custom widgets based on original SVG from Wikimedia Commons.
version: 1.0.12
homepage: https://github.com/loloof64/chess_vectors_flutter

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
